### ISSUE TITLE
Unhanded exception on reserve

### ISSUE THREAD

**Issue by stwalkerster** [enwikipedia-acc/waca#180]
There appears to be something wrong with the tool. On clicking 'Reserve' it shows an error as following,

```
Fatal error: Uncaught exception 'Exception' with message 'Error connectiong to database 'notifications': SQLSTATE[HY000] [2005] Unknown MySQL server host 'dbmaster.srv.stwalkerster.net' (110)' in /data/project/application/production/includes/PdoDatabase.php:35 
Stack trace: 
#0 /data/project/application/production/includes/DataObjects/Notification.php(108): gGetDb('notifications') 
#1 /data/project/application/production/includes/DataObjects/Notification.php(323): Notification::send('Request 133045 ...') 
#2 /data/project/application/production/acc.php(1723): Notification::requestReserved(Object(Request)) 
#3 /data/project/application/production/includes/PdoDatabase.php(112): {closure}() 
#4 /data/project/application/production/acc.php(1729): PdoDatabase->transactionally(Object(Closure)) 
#5 {main} thrown in /data/project/application/production/includes/PdoDatabase.php on line 35
```

Reported by Anup Mehra on mailing list

**Comment by stwalkerster** [comment]
It should be a simple case of adding a try/catch around everything in `Notification::send(...)`, and maybe logging it out somewhere.
