### ISSUE TITLE
Database deadlocks

### ISSUE THREAD

**Issue by stwalkerster** [enwikipedia-acc/waca#655]
We've had several deadlocks in the database.

### Deadlock 1
This one was encountered by me while deferring a request (txn 1); txn 2 is the "related requests from this IP" query.

```
2020-12-30 19:45:16 0x7fdc802a1700
*** (1) TRANSACTION:
TRANSACTION 225198, ACTIVE 0 sec updating or deleting
mysql tables in use 1, locked 1
LOCK WAIT 11 lock struct(s), heap size 1128, 19 row lock(s), undo log entries 1
UPDATE `request` SET
	status = 'Open',
	emailsent = '0',
	emailconfirm = 'Confirmed',
	reserved = NULL,
	updateversion = updateversion + 1
WHERE id = '298620' AND updateversion = '5'
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 543 page no 25 n bits 712 index acc_pend_status_mailconf of table `production`.`request` lock_mode X locks rec but not gap waiting


*** (2) TRANSACTION:
TRANSACTION 422062531277184, ACTIVE 0 sec fetching rows
mysql tables in use 1, locked 1
26 lock struct(s), heap size 3488, 97 row lock(s)
SELECT /* SearchHelper */ COUNT(*) FROM request origin  WHERE 1 = 1 AND (ip LIKE '1.2.3.4' OR forwardedip LIKE '%1.2.3.4%') AND emailconfirm = 'Confirmed' AND ip <> '127.0.0.1' AND email <> 'acc@toolserver.org' AND id <> '297963'
*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 543 page no 3848 n bits 120 index PRIMARY of table `production`.`request` trx id 422062531277184 lock mode S locks rec but not gap waiting

*** WE ROLL BACK TRANSACTION (1)
```

### Deadlock 2
We need to check where this is being done, as it feels like something which should be done as a background maintenance job, but it seems to be done at an odd time, and it's being done multiple times?

```
2020-11-29 16:18:52 0x7f4bbc5eb700
*** (1) TRANSACTION:
TRANSACTION 174553, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 252 lock struct(s), heap size 41080, 5608 row lock(s)
DELETE FROM antispoofcache WHERE timestamp < date_sub(now(), INTERVAL 3 HOUR)
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 530 page no 3 n bits 144 index PRIMARY of table `production`.`antispoofcache` trx id 174553 lock_mode X waiting
Record lock, heap no 57 PHYSICAL RECORD: n_fields 7; compact format; info bits 0

*** (2) TRANSACTION:
TRANSACTION 174554, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
252 lock struct(s), heap size 41080, 5608 row lock(s)
DELETE FROM antispoofcache WHERE timestamp < date_sub(now(), INTERVAL 3 HOUR)
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 530 page no 3 n bits 144 index PRIMARY of table `production`.`antispoofcache` trx id 174554 lock mode S
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 530 page no 3 n bits 144 index PRIMARY of table `production`.`antispoofcache` trx id 174554 lock_mode X waiting
Record lock, heap no 57 PHYSICAL RECORD: n_fields 7; compact format; info bits 0

```

This also occurred at 2020-11-20 01:42:43, 2020-11-14 03:50:17, and 2020-11-08 03:12:33

### Deadlock 3
This was a spam account request, so not a big deal that we lost the data from this.

```
#0 /srv/production/includes/DataObjects/Request.php(67): PDOStatement->execute()
#1 /srv/production/includes/Pages/Request/PageRequestAccount.php(157): Waca\DataObjects\Request->save()
#2 /srv/production/includes/Pages/Request/PageRequestAccount.php(64): Waca\Pages\Request\PageRequestAccount->saveAsEmailConfirmation(Object(Waca\DataObjects\Request), Object(Waca\DataObjects\Comment))
#3 /srv/production/includes/Tasks/PageBase.php(102): Waca\Pages\Request\PageRequestAccount->main()
#4 /srv/production/includes/Tasks/PageBase.php(361): Waca\Tasks\PageBase->runPage()
#5 /srv/production/includes/Tasks/PublicInterfacePageBase.php(23): Waca\Tasks\PageBase->execute()
#6 /srv/production/includes/WebStart.php(191): Waca\Tasks\PublicInterfacePageBase->execute()
#7 /srv/production/includes/WebStart.php(104): Waca\WebStart->main()
#8 /srv/production/index.php(27): Waca\WebStart->run()
#9 {main}
```

```
2020-12-30 20:03:46 0x7fdc802ec700
*** (1) TRANSACTION:
TRANSACTION 225336, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
LOCK WAIT 165 lock struct(s), heap size 24696, 2169 row lock(s), undo log entries 1
INSERT INTO `request` (
	email, ip, name, status, date, emailsent,
	emailconfirm, reserved, useragent, forwardedip
) VALUES (
	'email@address.example', '172.16.0.164', 'Ronalddot', 'Open', CURRENT_TIMESTAMP(), '0',
	'confirmhash', NULL, 'ua', 'ipaddr'
)
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 543 page no 3596 n bits 712 index acc_pend_status_mailconf of table `production`.`request` trx id 225336 lock_mode X locks gap before rec insert intention waiting
Record lock, heap no 533 PHYSICAL RECORD: n_fields 3; compact format; info bits 0

*** (2) TRANSACTION:
TRANSACTION 225337, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
165 lock struct(s), heap size 24696, 2169 row lock(s), undo log entries 1
INSERT INTO `request` (
	email, ip, name, status, date, emailsent,
	emailconfirm, reserved, useragent, forwardedip
) VALUES (
	'email@address.example', '172.16.0.164', 'Greggfen', 'Open', CURRENT_TIMESTAMP(), '0',
	'confirmhash', NULL, 'ua', 'ipaddr'
)
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 543 page no 3596 n bits 712 index acc_pend_status_mailconf of table `production`.`request` trx id 225337 lock mode S

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 543 page no 3596 n bits 712 index acc_pend_status_mailconf of table `production`.`request` trx id 225337 lock_mode X locks gap before rec insert intention waiting
Record lock, heap no 580 PHYSICAL RECORD: n_fields 3; compact format; info bits 0

*** WE ROLL BACK TRANSACTION (2)
```

**Comment by ElHefWiki** [comment]
@stwalkerster Job 1883 failed with the same error message as job 526 in March.
