### ISSUE TITLE
Unhandled exception on view request

### ISSUE THREAD

**Issue by stwalkerster** [enwikipedia-acc/waca#720]
Exception details:
`Call to a member function getHeader() on null`

Stack trace:
```
#0 ./vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_61e07204dc82a1_20931511(Object(Smarty_Internal_Template))
#1 ./vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#2 ./vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#3 ./vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#4 ./templates_c/fb9ae77a09c6b0af5db6dec25d53fd9f4820e2af_0.file.main.tpl.php(204): Smarty_Internal_Template->_subTemplateRender('file:view-reque...', NULL, NULL, 0, 3600, Array, 0, false)
...
#31 ./includes/Fragments/TemplateOutput.php(115): Smarty_Internal_TemplateBase->fetch('view-request/ma...')
#32 ./includes/Tasks/PageBase.php(174): Waca\Tasks\PageBase->fetchTemplate('view-request/ma...')
#33 ./includes/Tasks/InternalPageBase.php(87): Waca\Tasks\PageBase->runPage()
#34 ./includes/WebStart.php(191): Waca\Tasks\InternalPageBase->execute()
#35 ./includes/WebStart.php(104): Waca\WebStart->main()
#36 ./internal.php(24): Waca\WebStart->run()
#37 {main}
````

`$_SERVER['REQUEST_URI'] = /internal.php/viewRequest?id=315435`

----

The interesting frame here is `#4`, which points to a compiled template. The relevant line of that compiled template is:

```
    204                             <?php $_smarty_tpl->_subTemplateRender("file:view-request/related-requests.tpl", $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, 0, $_smarty_tpl->cache_lifetime, array('requ    204 ests'=>$_smarty_tpl->tpl_vars['requestRelatedEmailRequests']->value), 0, false);
```

This isn't the top of the stack, so it's something _within Smarty_ during the render blowing up, but importantly it's _within the `related-requests.tpl` template_. The only thing that looks remotely like `getHeader()` is [this](https://github.com/enwikipedia-acc/waca/blob/b88efb56e89ade9e744ee9db2ee97533e5cb92a7/templates/view-request/related-requests.tpl#L15).

The bug was reported to have resolved itself after a short while.

**Comment by stwalkerster** [comment]
OK, reproduced and confirmed my thinking.

If two requests exist and are "related" in some way (sharing IP or email), and one of them is in the hospital queue, then browsing to the other one will try and dereference the null queue (because hospital is a status, not an open+enqueued request), which throws this bug.
